[versions]
spring-boot = "3.5.3"
doma = "3.9.1"
doma-boot = "2.4.0"
jackson = "2.19.0"
jsqlparser = "5.3"
javaparser = "3.27.0"
picocli = "4.7.7"
snakeyaml = "2.4"
opentelemetry = "1.51.0"
postgresql = "42.7.7"
flyway = "11.8.2"
springdoc = "2.8.6"
junit = "5.12.2"
assertj = "3.27.3"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jsqlparser = { module = "com.github.jsqlparser:jsqlparser", version.ref = "jsqlparser" }
javaparser = { module = "com.github.javaparser:javaparser-symbol-solver-core", version.ref = "javaparser" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
doma-core = { module = "org.seasar.doma:doma-core", version.ref = "doma" }
doma-processor = { module = "org.seasar.doma:doma-processor", version.ref = "doma" }
doma-spring-boot = { module = "org.seasar.doma.boot:doma-spring-boot-starter", version.ref = "doma-boot" }
springdoc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
