. (Join-Path $PSScriptRoot 'lib.ps1')
Import-MandalaEnv

if (-not $env:BACKEND_PORT) { $env:BACKEND_PORT = '18080' }
$baseUrl = "http://127.0.0.1:$($env:BACKEND_PORT)"
$traceFile = Join-Path $script:MandalaRepositoryRoot 'mandala/traces/runtime/otlp.json'
$snapshotDir = Join-Path $script:MandalaRepositoryRoot 'mandala/snapshots/runtime'
New-Item -ItemType Directory -Path (Split-Path -Parent $traceFile), $snapshotDir -Force | Out-Null
Wait-MandalaHttp "$baseUrl/actuator/health" 'Sample backend' 10

Write-MandalaLog 'Resetting the generated trace file and Collector file handle.'
Invoke-MandalaCompose stop otel-collector
Remove-Item -LiteralPath $traceFile -Force -ErrorAction SilentlyContinue
& docker run --rm --volume 'mandala-sbdp-traces:/data' alpine:3.22.0 rm -f /data/otlp.json *> $null
if ($LASTEXITCODE -ne 0) { throw 'Could not reset the local trace volume.' }
Invoke-MandalaCompose up --detach otel-collector
Wait-MandalaHttp 'http://127.0.0.1:13133/' 'OpenTelemetry Collector' 60

$userSession = [Microsoft.PowerShell.Commands.WebRequestSession]::new()
$adminSession = [Microsoft.PowerShell.Commands.WebRequestSession]::new()
$projectId = $null
$taskId = $null

function Assert-MandalaFailureStatus {
    param(
        [Parameter(Mandatory)][string]$Uri,
        [Parameter(Mandatory)][int]$ExpectedStatus,
        [Parameter(Mandatory)][Microsoft.PowerShell.Commands.WebRequestSession]$Session,
        [string]$Method = 'Get',
        [string]$Body,
        [Parameter(Mandatory)][string]$FlowId
    )
    $request = @{
        Uri = $Uri
        Method = $Method
        WebSession = $Session
        Headers = @{ 'X-Mandala-Flow-Id' = $FlowId }
        UseBasicParsing = $true
    }
    if ($Body) {
        $request.ContentType = 'application/json'
        $request.Body = $Body
    }
    $actualStatus = 0
    try {
        $actualStatus = (Invoke-WebRequest @request).StatusCode
    } catch {
        if ($_.Exception.Response -and $_.Exception.Response.StatusCode) {
            $actualStatus = [int]$_.Exception.Response.StatusCode
        } else {
            throw
        }
    }
    if ($actualStatus -ne $ExpectedStatus) {
        throw "Expected HTTP $ExpectedStatus from $Uri, got $actualStatus."
    }
}

try {
    Write-MandalaLog 'Executing real login and CRUD requests.'
    Assert-MandalaFailureStatus -Uri "$baseUrl/api/projects" -ExpectedStatus 401 -Session $userSession -FlowId 'unauthenticated'
    $userLogin = @{ username = 'local-user'; password = 'mandala-user' } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$baseUrl/api/auth/login" -Method Post -ContentType 'application/json' -Body $userLogin -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'login.success' } | Out-Null

    $invalidProject = @{ name = '   ' } | ConvertTo-Json -Compress
    Assert-MandalaFailureStatus -Uri "$baseUrl/api/projects" -ExpectedStatus 400 -Session $userSession -Method Post -Body $invalidProject -FlowId 'project.create.validation'
    Assert-MandalaFailureStatus -Uri "$baseUrl/api/projects/1" -ExpectedStatus 403 -Session $userSession -FlowId 'forbidden'

    $projectBody = @{ name = 'PowerShell runtime capture'; description = 'Generated by capture-runtime.ps1' } | ConvertTo-Json -Compress
    $project = Invoke-RestMethod -Uri "$baseUrl/api/projects" -Method Post -ContentType 'application/json' -Body $projectBody -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'project.create.success' }
    $projectId = $project.id
    Invoke-RestMethod -Uri "$baseUrl/api/projects/$projectId" -Method Get -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'project.detail' } | Out-Null

    $updatedProject = @{ name = 'PowerShell runtime capture updated'; description = 'Doma update' } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$baseUrl/api/projects/$projectId" -Method Put -ContentType 'application/json' -Body $updatedProject -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'project.update' } | Out-Null

    $taskBody = @{ title = 'PowerShell capture task'; description = 'Doma insert' } | ConvertTo-Json -Compress
    $task = Invoke-RestMethod -Uri "$baseUrl/api/projects/$projectId/tasks" -Method Post -ContentType 'application/json' -Body $taskBody -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'task.create' }
    $taskId = $task.id
    Invoke-RestMethod -Uri "$baseUrl/api/tasks/$taskId" -Method Get -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'task.detail' } | Out-Null

    $updatedTask = @{ title = 'PowerShell capture task updated'; description = 'Doma update'; status = 'IN_PROGRESS' } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$baseUrl/api/tasks/$taskId" -Method Put -ContentType 'application/json' -Body $updatedTask -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'task.update' } | Out-Null
    $statusBody = @{ status = 'DONE' } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$baseUrl/api/tasks/$taskId/status" -Method Patch -ContentType 'application/json' -Body $statusBody -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'task.status.change' } | Out-Null

    Invoke-WebRequest -Uri "$baseUrl/v3/api-docs" -OutFile (Join-Path $snapshotDir 'openapi.json') -UseBasicParsing
    $adminLogin = @{ username = 'local-admin'; password = 'mandala-admin' } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$baseUrl/api/auth/login" -Method Post -ContentType 'application/json' -Body $adminLogin -WebSession $adminSession | Out-Null
    Invoke-WebRequest -Uri "$baseUrl/actuator/mappings" -WebSession $adminSession -OutFile (Join-Path $snapshotDir 'actuator-mappings.json') -UseBasicParsing
} finally {
    if ($taskId) {
        try { Invoke-RestMethod -Uri "$baseUrl/api/tasks/$taskId" -Method Delete -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'task.delete' } | Out-Null } catch { Write-Warning $_ }
    }
    if ($projectId) {
        try { Invoke-RestMethod -Uri "$baseUrl/api/projects/$projectId" -Method Delete -WebSession $userSession -Headers @{ 'X-Mandala-Flow-Id' = 'project.delete' } | Out-Null } catch { Write-Warning $_ }
    }
}

function Get-MandalaSpanAttribute {
    param([Parameter(Mandatory)]$Span, [Parameter(Mandatory)][string]$Key)
    foreach ($attribute in @($Span.attributes)) {
        if ($attribute.key -eq $Key) { return $attribute.value.stringValue }
    }
    return $null
}

function Test-MandalaProjectTrace {
    param([Parameter(Mandatory)][string]$Path)
    $spans = [System.Collections.Generic.List[object]]::new()
    try {
        foreach ($line in Get-Content -LiteralPath $Path) {
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            $document = $line | ConvertFrom-Json
            foreach ($resourceSpans in @($document.resourceSpans)) {
                foreach ($scopeSpans in @($resourceSpans.scopeSpans)) {
                    foreach ($span in @($scopeSpans.spans)) { $spans.Add($span) }
                }
            }
        }
    } catch {
        return $false
    }
    $projectTraceId = $null
    foreach ($span in $spans) {
        if ((Get-MandalaSpanAttribute -Span $span -Key 'mandala.flow.id') -eq 'project.create.success') {
            $projectTraceId = $span.traceId
            break
        }
    }
    if (-not $projectTraceId) { return $false }
    $layers = @()
    $hasDatabaseSpan = $false
    foreach ($span in $spans) {
        if ($span.traceId -ne $projectTraceId) { continue }
        $layer = Get-MandalaSpanAttribute -Span $span -Key 'mandala.layer'
        if ($layer) { $layers += $layer }
        foreach ($key in 'db.system.name', 'db.system', 'db.operation.name') {
            if (Get-MandalaSpanAttribute -Span $span -Key $key) { $hasDatabaseSpan = $true }
        }
    }
    return $hasDatabaseSpan `
        -and 'http_server' -in $layers `
        -and 'application_service' -in $layers `
        -and 'doma_dao' -in $layers
}

$traceCopied = $false
$candidateTrace = Join-Path ([System.IO.Path]::GetTempPath()) "mandala-otlp-$([guid]::NewGuid().ToString('N')).json"
$lastFingerprint = ''
$stableCopies = 0
for ($attempt = 1; $attempt -le 30; $attempt++) {
    Remove-Item -LiteralPath $candidateTrace -Force -ErrorAction SilentlyContinue
    try {
        Invoke-MandalaCompose cp 'otel-collector:/var/lib/mandala-traces/otlp.json' $candidateTrace
    } catch {
        # The file exporter has not flushed its first batch yet.
    }
    if ((Test-Path -LiteralPath $candidateTrace) -and (Get-Item -LiteralPath $candidateTrace).Length -gt 0) {
        $validJsonLines = $true
        foreach ($line in Get-Content -LiteralPath $candidateTrace) {
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            try { $line | ConvertFrom-Json | Out-Null } catch { $validJsonLines = $false; break }
        }
        if ($validJsonLines -and (Test-MandalaProjectTrace -Path $candidateTrace)) {
            $fingerprint = (Get-FileHash -LiteralPath $candidateTrace -Algorithm SHA256).Hash
            if ($fingerprint -eq $lastFingerprint) {
                $stableCopies++
            } else {
                $lastFingerprint = $fingerprint
                $stableCopies = 1
            }
            # Cross a complete quiet window after the first reference trace so
            # late Java batch-processor exports cannot leave a detached trace.
            if ($stableCopies -ge 8) {
                Copy-Item -LiteralPath $candidateTrace -Destination $traceFile -Force
                $traceCopied = $true
                break
            }
        } else {
            $lastFingerprint = ''
            $stableCopies = 0
        }
    }
    Start-Sleep -Seconds 1
}
Remove-Item -LiteralPath $candidateTrace -Force -ErrorAction SilentlyContinue
if (-not $traceCopied) {
    throw "Collector did not write a complete and stable project-create OTLP trace to $traceFile. Check .runtime/logs/backend.log and Docker logs."
}
$traceText = Get-Content -LiteralPath $traceFile -Raw
if ($traceText -match '(?i)mandala-(admin|user)|bearer\s+[a-z0-9._-]{8,}|"key"\s*:\s*"[^"]*(authorization|cookie|password|token)[^"]*"') {
    throw 'A local credential or sensitive header was found in the captured trace.'
}

if (-not (Test-MandalaProjectTrace -Path $traceFile)) {
    throw 'Project-create trace does not contain HTTP, service, DAO and database spans in one trace.'
}

$openApi = Get-Content -LiteralPath (Join-Path $snapshotDir 'openapi.json') -Raw | ConvertFrom-Json
if (@($openApi.paths.PSObject.Properties).Count -lt 10) { throw 'Captured OpenAPI contains fewer than 10 paths.' }
$mappings = Get-Content -LiteralPath (Join-Path $snapshotDir 'actuator-mappings.json') -Raw | ConvertFrom-Json
if (-not $mappings.contexts) { throw 'Captured Actuator mappings do not contain contexts.' }
Write-MandalaLog 'Runtime traces, OpenAPI and Actuator mappings captured.'
