create table users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    role varchar(20) not null check (role in ('ADMIN', 'USER')),
    enabled boolean not null default true,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

create table projects (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references users(id) on delete restrict,
    name varchar(120) not null check (length(trim(name)) > 0),
    description varchar(2000) not null default '',
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

create table tasks (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects(id) on delete cascade,
    title varchar(200) not null check (length(trim(title)) > 0),
    description varchar(5000) not null default '',
    status varchar(20) not null check (status in ('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED')),
    assignee_id bigint references users(id) on delete set null,
    due_date date,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id) on delete set null,
    action varchar(40) not null,
    entity_type varchar(40) not null,
    entity_id bigint,
    details text not null default '{}',
    created_at timestamp without time zone not null
);

create index projects_owner_id_idx on projects(owner_id);
create index tasks_project_id_idx on tasks(project_id);
create index tasks_assignee_id_idx on tasks(assignee_id);
create index tasks_status_idx on tasks(status);
create index audit_logs_entity_idx on audit_logs(entity_type, entity_id);
create index audit_logs_created_at_idx on audit_logs(created_at desc);

comment on table users is 'Local accounts used for session authentication';
comment on column users.password_hash is 'BCrypt password hash; plaintext passwords are never persisted';
comment on table projects is 'Task-management projects owned by a user';
comment on table tasks is 'Work items belonging to a project';
comment on table audit_logs is 'Immutable application mutation and authentication audit trail';
